version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully!!
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - /codebuild/output/src615478493/src/target/spring-boot-rest-1.0-SNAPSHOT.war
  discard-paths: yes